defaults:
  startdate: "1990-01-01"

series:
  # --- CHINA (monthly) ---
  - {code: n924d@emergepr, frequency: monthly}
  - {code: n924trs@emergepr, frequency: monthly}
  - {code: n924vr@emergepr, frequency: monthly}
  - {code: n924fczm@emergepr, frequency: monthly}
  - {code: n924ixd@emergepr, frequency: monthly}
  - {code: n924imd@emergepr, frequency: monthly}
  - {code: s924vm@emergepr, frequency: monthly}
  - {code: s924vng@emergepr, frequency: monthly}
  - {code: h924vcc@emergepr, frequency: monthly}
  - {code: n924vfci@emergepr, frequency: monthly}
  - {code: n924pcy@emergepr, frequency: monthly}
  - {code: n924pcxg@emergepr, frequency: monthly}
  - {code: n924pcyf@emergepr, frequency: monthly}
  - {code: n924pci@emergepr, frequency: monthly}
  - {code: n924pcs@emergepr, frequency: monthly}
  - {code: h924pc@emergepr, frequency: monthly}
  - {code: h924pcxz@emergepr, frequency: monthly}
  - {code: h924pcff@emergepr, frequency: monthly}
  - {code: h924pji@emergepr, frequency: monthly}
  - {code: h924pjs@emergepr, frequency: monthly}
  - {code: n924trs2@emergepr, frequency: monthly}
  - {code: n924trsc@emergepr, frequency: monthly}
  - {code: n924tsfb@emergepr, frequency: monthly}
  - {code: n924tspp@emergepr, frequency: monthly}
  - {code: n924tsau@emergepr, frequency: monthly}
  - {code: n924tscd@emergepr, frequency: monthly}
  - {code: h924d@emergepr, frequency: monthly}
  - {code: n924dvgg@emergepr, frequency: monthly}
  - {code: n924dvgm@emergepr, frequency: monthly}
  - {code: n924dvgp@emergepr, frequency: monthly}
  - {code: s924vmg@emergepr, frequency: monthly}
  - {code: s924mg@mktpmi, frequency: monthly}
  - {code: y924vr@emergepr, frequency: monthly}
  - {code: y924vr1@emergepr, frequency: monthly}
  - {code: y924vr2@emergepr, frequency: monthly}
  - {code: y924vr3@emergepr, frequency: monthly}
  - {code: n924vvr@emergepr, frequency: monthly}
  - {code: n924vrds@emergepr, frequency: monthly}
  - {code: n924vrrd@emergepr, frequency: monthly}
  - {code: n924fczg@emergepr, frequency: monthly}
  - {code: n924fczb@emergepr, frequency: monthly}
  - {code: n924fczn@emergepr, frequency: monthly}
  - {code: n924iqxp@emergepr, frequency: monthly}
  - {code: n924iqmp@emergepr, frequency: monthly}
  - {code: n924ix@emergepr, frequency: monthly}
  - {code: n924im@emergepr, frequency: monthly}
  - {code: n924ixa4@emergepr, frequency: monthly}
  - {code: n924ixjp@emergepr, frequency: monthly}
  - {code: n924ixeu@emergepr, frequency: monthly}
  - {code: n924ixus@emergepr, frequency: monthly}
  - {code: h924ixd@emergepr, frequency: monthly}
  - {code: h924imd@emergepr, frequency: monthly}
  - {code: h924ix@emergepr, frequency: monthly}
  - {code: h924im@emergepr, frequency: monthly}
  - {code: n924euru@emergepr, frequency: monthly}
  - {code: n924fzn9@emergepr, frequency: monthly}
  - {code: s924vme@emergepr, frequency: monthly}
  - {code: s924vnes@emergepr, frequency: monthly}
  - {code: s924vnec@emergepr, frequency: monthly}
  - {code: s924me@mktpmi, frequency: monthly}
  - {code: s924se@mktpmi, frequency: monthly}
  - {code: s924vmo@emergepr, frequency: monthly}
  - {code: s924vmsr@emergepr, frequency: monthly}
  - {code: s924vmd@emergepr, frequency: monthly}
  - {code: s924m@mktpmi, frequency: monthly}
  - {code: s924mo@mktpmi, frequency: monthly}
  - {code: s924vngc@emergepr, frequency: monthly}
  - {code: s924vnoc@emergepr, frequency: monthly}
  - {code: s924vngs@emergepr, frequency: monthly}
  - {code: s924vnos@emergepr, frequency: monthly}
  - {code: s924s@mktpmi, frequency: monthly}
  - {code: s924spc@mktpmi, frequency: monthly}
  - {code: s924snb@mktpmi, frequency: monthly}

  # --- JAPAN (monthly) ---
  - {code: jpsiip@japan, frequency: monthly}
  - {code: jpfaral2@japan, frequency: monthly}
  - {code: jpewfra2@japan, frequency: monthly}
  - {code: omnn2@japan, frequency: monthly}
  - {code: bngx2@japan, frequency: monthly}
  - {code: m158m@mktpmi, frequency: monthly}
  - {code: m158s@mktpmi, frequency: monthly}
  - {code: ccia@japan, frequency: monthly}
  - {code: jpcij@japan, frequency: monthly}
  - {code: jpcij2@japan, frequency: monthly}
  - {code: jpcijef@japan, frequency: monthly}
  - {code: jpcijef2@japan, frequency: monthly}
  - {code: jpcije@japan, frequency: monthly}
  - {code: jpcije2@japan, frequency: monthly}
  - {code: jpcit@japan, frequency: monthly}
  - {code: jpcit2@japan, frequency: monthly}
  - {code: jpcitef@japan, frequency: monthly}
  - {code: jpcitef2@japan, frequency: monthly}
  - {code: jpnce@japan, frequency: monthly}
  - {code: jpncfxf@japan, frequency: monthly}
  - {code: jpcijff@japan, frequency: monthly}
  - {code: jpsir@japan, frequency: monthly}
  - {code: jpscaic@japan, frequency: monthly}
  - {code: jpscaidc@japan, frequency: monthly}
  - {code: jpscaisc@japan, frequency: monthly}
  - {code: jpsir2@japan, frequency: monthly}
  - {code: cdai@japan, frequency: monthly}
  - {code: cdae@japan, frequency: monthly}
  - {code: cdad@japan, frequency: monthly}
  - {code: jpniip@japan, frequency: monthly}
  - {code: jpniipf@japan, frequency: monthly}
  - {code: jpniipfi@japan, frequency: monthly}
  - {code: jpniipct@japan, frequency: monthly}
  - {code: jpsiipf@japan, frequency: monthly}
  - {code: jpsiipfi@japan, frequency: monthly}
  - {code: jpsiipct@japan, frequency: monthly}
  - {code: m158mg@mktpmi, frequency: monthly}
  - {code: m158mo@mktpmi, frequency: monthly}
  - {code: jptis@japan, frequency: monthly}
  - {code: jpstiewr@japan, frequency: monthly}
  - {code: jptiseps@japan, frequency: monthly}
  - {code: jptisebs@japan, frequency: monthly}
  - {code: m158se@mktpmi, frequency: monthly}
  - {code: m158snb@mktpmi, frequency: monthly}
  - {code: m158sx@mktpmi, frequency: monthly}
  - {code: omnn@japan, frequency: monthly}
  - {code: costsn@japan, frequency: monthly}
  - {code: costs@japan, frequency: monthly}
  - {code: cnorv@japan, frequency: monthly}
  - {code: jpsivm@japan, frequency: monthly}
  - {code: costsn2@japan, frequency: monthly}
  - {code: costs2@japan, frequency: monthly}
  - {code: cnorv2@japan, frequency: monthly}
  - {code: fluedr2@japan, frequency: monthly}
  - {code: flpr@japan, frequency: monthly}
  - {code: mefac@japan, frequency: monthly}
  - {code: mefcac@japan, frequency: monthly}
  - {code: jpwtcei2@japan, frequency: monthly}
  - {code: jpwccei2@japan, frequency: monthly}
  - {code: m158me@mktpmi, frequency: monthly}
  - {code: m158md@mktpmi, frequency: monthly}
  - {code: m158mpi@mktpmi, frequency: monthly}
  - {code: m158mpo@mktpmi, frequency: monthly}
  - {code: m158mx@mktpmi, frequency: monthly}
  - {code: m158spi@mktpmi, frequency: monthly}
  - {code: m158spc@mktpmi, frequency: monthly}
  - {code: m158swo@mktpmi, frequency: monthly}
  - {code: jpitwvx@japan, frequency: monthly}
  - {code: jpitwvm@japan, frequency: monthly}
  - {code: jpituvx@japan, frequency: monthly}
  - {code: jpitevx@japan, frequency: monthly}
  - {code: jpitcvx@japan, frequency: monthly}
  - {code: bngm2@japan, frequency: monthly}
  - {code: jpnscx12@japan, frequency: monthly}
  - {code: jpnsdx12@japan, frequency: monthly}
  - {code: jpsivx@japan, frequency: monthly}
  - {code: jpsivxcn@japan, frequency: monthly}
  - {code: jpsivxeu@japan, frequency: monthly}
  - {code: jpsivxna@japan, frequency: monthly}
  - {code: jpsivxus@japan, frequency: monthly}

  # --- JAPAN (quarterly) ---
  - {code: jsngpcp@japan, frequency: quarterly}
  - {code: jsnpccp@japan, frequency: quarterly}
  - {code: jsndfcp@japan, frequency: quarterly}
  - {code: jsnescp@japan, frequency: quarterly}
  - {code: saoa1a@japan, frequency: quarterly}
  - {code: saoa3a@japan, frequency: quarterly}
  - {code: saoa5a@japan, frequency: quarterly}